name: CI Tests

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - run: yarn install
      - run: yarn build
      - run: yarn test
