name: Docs

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: rm -rf docs
      - run: mkdir docs
      - run: yarn workspace @dimension/homepage build:gh
      - run: cp -a ./packages/homepage/dist/. ./docs
      - run: yarn workspace @dimension/core docs
      - run: cp -a ./packages/core/docs/. ./docs/api
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v1.2.5
        with:
          # Build directory to deploy
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
